spring:

  application:
    name: StoreReservation

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store_reservation
    username: root
    password: zerozero

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경에 따라 데이터베이스 스키마를 자동으로 업데이트
    show-sql: true
    database: mysql